Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile('public\muesli.jpg')
$bmp = New-Object System.Drawing.Bitmap($img)
$img.Dispose()
$g = [System.Drawing.Graphics]::FromImage($bmp)
$rect = New-Object System.Drawing.Rectangle(500, 750, 150, 40)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(233, 227, 219))
$g.FillRectangle($brush, $rect)
$font = New-Object System.Drawing.Font('Arial', 24, [System.Drawing.FontStyle]::Bold)
$textBrush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::Black)
$g.DrawString('? 185', $font, $textBrush, 500, 750)
$bmp.Save('public\muesli.jpg', [System.Drawing.Imaging.ImageFormat]::Jpeg)
$g.Dispose()
$bmp.Dispose()
